name: Cloudnotes CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout 
        uses: actions/checkout@v4
      
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install backend dependencies 
        working-directory: ./backend
        run: npm ci

      - name: build backend 
        working-directory: ./backend
        run: npm run build

      - name: install frontend dependencies 
        working-directory: ./frontend
        run: npm ci

      - name: build frontend
        working-directory: ./frontend
        run: npm run build

     
        

      