name: Cloudnotes CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: build backend
        working-directory: ./backend
        run: npm run build

      - name: install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: build frontend
        working-directory: ./frontend
        run: npm run build

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build backend docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cloudnotes-backend:latest

      - name: build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cloudnotes-frontend:latest

      # Deploy to existing EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$EC2_SSH_KEY" > ~/.ssh/cloudnotes.pem
          chmod 600 ~/.ssh/cloudnotes.pem

          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/cloudnotes.pem "$EC2_USER@$EC2_HOST" << EOF
            cd /home/ubuntu/cloudnotes

            echo "$GHCR_TOKEN" | docker login ghcr.io \
              -u "${{ github.actor }}" \
              --password-stdin

            docker compose pull

            docker compose up -d

            docker image prune -f
          EOF